spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt_practice
    username: root
    password: 1q2w3e4r!
#  sql:
#    init:
#      mode: always
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
#    defer-datasource-initialization: true
#    generate-ddl: true

